"""Add player_id to Character

Revision ID: 14c02149c82a
Revises: 
Create Date: 2024-07-25 01:47:31.055739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c02149c82a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_column('health_points')
        batch_op.drop_column('is_alive')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_alive', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('health_points', sa.INTEGER(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
