"""Add referee prompts table

Revision ID: 17de48fae80c
Revises: df25bfba78f5
Create Date: 2024-07-21 19:02:34.530004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17de48fae80c'
down_revision = 'df25bfba78f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referee_prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referee_prompt')
    # ### end Alembic commands ###
