"""Add commentator prompts table

Revision ID: 48772a6d734c
Revises: 17de48fae80c
Create Date: 2024-07-21 19:28:24.626024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48772a6d734c'
down_revision = '17de48fae80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentator_prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commentator_prompt')
    # ### end Alembic commands ###
