"""Initial migration

Revision ID: 53ea5f9f774e
Revises: 
Create Date: 2024-08-10 13:14:44.296007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ea5f9f774e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('selected_character_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('player_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'player', ['player_id'], ['id'])

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_character_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'character', ['selected_character_id'], ['id'])

    # ### end Alembic commands ###
