"""Add read_status to ArenaChatMessage

Revision ID: 54f876cd9fe0
Revises: 
Create Date: 2024-08-02 18:00:18.861284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f876cd9fe0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arena_chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arena_chat_message', schema=None) as batch_op:
        batch_op.drop_column('read_status')

    # ### end Alembic commands ###
