"""Add read_status to TacticsChatMessage

Revision ID: c633a1e276fc
Revises: 54f876cd9fe0
Create Date: 2024-08-03 19:32:08.103155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c633a1e276fc'
down_revision = '54f876cd9fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tactics_chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tactics_chat_message', schema=None) as batch_op:
        batch_op.drop_column('read_status')

    # ### end Alembic commands ###
